### ISSUE TITLE
컨테이너 사이 구분선 추가

### ISSUE THREAD

**Issue by hye-inA** [hye-inA/flutter_dev#1]
# Issue
1. 각 사용자 프로필 내부의 마지막 Column 컨테이너에서 2개의 아이콘 컨테이너를 집어넣음
두 아이콘 사이에 구분선 구현 부분에서 어떻게 구현해야할지 막힘

2. 각 사용자 프로필 내부의 컨테이너들 사이의 간격 조절 리펙토링 필요

<img width="402" alt="스크린샷 2024-03-10 오후 9 33 12" src="https://github.com/hye-inA/flutter_dev/assets/128613248/0d4e20c9-c773-4105-8b0b-2e523361a94c">

# Todo
- 구분선 구현 
- 스크롤 기능 공부

**Comment by doyle-flutter** [comment]
LGTM 👍
