### ISSUE TITLE
Refactor : List-View 위젯으로 변경 

### ISSUE THREAD

**Issue by hye-inA** [hye-inA/flutter_dev#2]
issue #1 에서는 프로필 Container들을 추가적으로 넣었을때 Bottom Overflow가 발생하는 상황이었기 때문에 
body 영역의 Column 위젯을 스크롤이 가능한 위젯인 'List-View'위젯으로 변경하여 해결함

<img width="573" alt="스크린샷 2024-03-13 오후 3 21 37" src="https://github.com/hye-inA/flutter_dev/assets/128613248/952252a4-bb20-4c85-935a-9995d8c45541">

**Comment by doyle-flutter** [comment]
이전 내용을 충분히 반영한 것으로 보입니다, 다음 수업 이후 얼마나 많은 내용이 변화될지 기대가 됩니다 :)
이전 건과 해당 건은 이정도로 마무리하여 이슈를 닫으면 될 것 같습니다.
